# Generated by Django 5.0 on 2026-01-21 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='novedades/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.IntegerField(unique=True)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
