# Generated by Django 5.0 on 2026-01-21 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='novedad',
            old_name='codigo',
            new_name='nro_novedad',
        ),
    ]
