# Generated by Django 5.0 on 2026-01-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novedades', '0002_rename_codigo_novedad_nro_novedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedad',
            name='nro_novedad',
        ),
    ]
